export const AZURE_COSMOS_DB_MODULE_OPTIONS = 'AZURE_COSMOS_DB_MODULE_OPTIONS';
export const AZURE_COSMOS_DB_CONNECTION_NAME = 'AZURE_COSMOS_DB_CONNECTION_NAME';
export const AZURE_COSMOS_DB_NAME = 'AZURE_COSMOS_DB_NAME';
export const DEFAULT_DB_CONNECTION = 'AZURE_COSMOS_DB_DEFAULT_CONNECTION';
