export const COSMOS_DB_MODULE_OPTIONS = 'COSMOS_DB_MODULE_OPTIONS';
export const COSMOS_DB_CONNECTION_NAME = 'COSMOS_DB_CONNECTION_NAME';
export const COSMOS_DB_NAME = 'COSMOS_DB_NAME';
export const DEFAULT_DB_CONNECTION = 'COSMOS_DB_DEFAULT_CONNECTION';
